// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL19y8PdFMggrIpIoX4R0g9SCZPcUCmgw',
    appId: '1:753698874161:web:dd5fbfebf958004a740610',
    messagingSenderId: '753698874161',
    projectId: 'fir-flutter-codelab-2faf4',
    authDomain: 'fir-flutter-codelab-2faf4.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-2faf4.appspot.com',
    measurementId: 'G-QFK6H9QMTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPpY21xxXFvlEM7nnODYmbn8ougBQMVns',
    appId: '1:753698874161:android:151e0dc432269053740610',
    messagingSenderId: '753698874161',
    projectId: 'fir-flutter-codelab-2faf4',
    storageBucket: 'fir-flutter-codelab-2faf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbbJugQdRYx2NVgjQUwfZ4wmbF4_Z2jq8',
    appId: '1:753698874161:ios:d616aca08720569b740610',
    messagingSenderId: '753698874161',
    projectId: 'fir-flutter-codelab-2faf4',
    storageBucket: 'fir-flutter-codelab-2faf4.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbbJugQdRYx2NVgjQUwfZ4wmbF4_Z2jq8',
    appId: '1:753698874161:ios:d616aca08720569b740610',
    messagingSenderId: '753698874161',
    projectId: 'fir-flutter-codelab-2faf4',
    storageBucket: 'fir-flutter-codelab-2faf4.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
